### ISSUE TITLE
Release 0.5.1

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic-responses#20]
Howdy @stephanbuys! Do you mind released the current `0.5.1` on crates.io? Thanks :)

**Comment by stephanbuys** [comment]
Done, only a pleasure :-) Sorry for going quiet - we're working on a bunch of other things atm.

**Comment by KodrAus** [comment]
No worries :) it's not urgent stuff so there's no hurry. Thanks for the release.
