### ISSUE TITLE
Release optional max_score fix

### ISSUE THREAD

**Issue by joprice** [elastic-rs/elastic-responses#25]
I just struggled through this one: https://github.com/elastic/elasticsearch/issues/266, and found that you already have it fixed on master. I'm adding 'track_scores: true' as a workaround for now, but curious when the next release will be.

**Comment by KodrAus** [comment]
Hi @joprice, you mean the change to make `score` optional? I was going to wait until merging #24 first, but if this is blocking you we can push out a release sooner for you.

Are you able to release `0.6` @stephanbuys?

**Comment by joprice** [comment]
Yes, exactly. No rush. I'm not blocked on anything critical.

**Comment by stephanbuys** [comment]
@KodrAus, pushed the release.

**Comment by KodrAus** [comment]
Legend! Thanks @stephanbuys

@joprice I'll close this off for now but please let us know if it doesn't work and I'll re-open.
