### ISSUE TITLE
Flesh out Hits type

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic-responses#6]
The generic `Deserialize` stuff I did is actually broken, because the `T` used for the hits type then needs to specify all the meta properties:

```json
{
  "_index" : "typed_sample_index",
  "_type" : "mytype",
  "_id" : "AVmGgFk0Y2GdL7rFge-6",
  "_score" : 1.0,
  "_source" : {
    "id" : 1,
    "title" : "A title"
  }
}
```

Maybe we can flesh out the `Hit` struct to hold this data and use the `_source` field for the `T`?

**Comment by stephanbuys** [comment]
I'm happy to do that, was wondering about it when I did the original types, can we be certain that those fields will always be present?

**Comment by KodrAus** [comment]
That's a good question, because if you specify a [`filter_path`](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/common-options.html#common-options-response-filtering) you can exclude fields from the response. If you're going to mess with things though I think it's reasonable to define your own response type...

Maybe we leave the `T` as is, and a caller can just specify a `ResponseOf<Hit<T>>` where `T` is their document struct? Then if they're excluding fields they can define their own `Hit` type.

I had a poke through the .NET client and it has the following properties on its `Hit`:

- `fields`
- `_source`
- `_index`
- `inner_hits`
- `_score`
- `_type`
- `_version`
- `_id`
- `_nested`
- `_parent`
- `_routing`
- `sort`
- `highlight`
- `_explanation`
- `matched_queries`

A lot of those would be contextual. The fields in my example above are from a basic `query_string` query, I guess `_version` would probably also be common once it's greater than 1.

**Comment by stephanbuys** [comment]
I like the `ResponseOf<Hit<T>>` idea. I'm not 100% sure, but I think its possible to use something like: `_id: Option<String>` and make those fields optional - otherwise we might have to define "`defaults()`" for it as in  https://serde.rs/attributes.html

**Comment by KodrAus** [comment]
@stephanbuys I'm working on this now, and adding some types for common error responses. I'm not stressing too much about all the fields above, since if anyone has problems they can fall back to `serde_json::Value` until we implement it. Sound reasonable?
