### ISSUE TITLE
Specific Response Parsing

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic-responses#9]
I'm working on a feature in `elastic` for figuring out what kind of a response you've got and deserialising the right one. See [here](https://github.com/elastic-rs/elastic/blob/eabb22675dba34eec285f57a7b3675fc3c3b2a55/src/client.rs#L26-L200).

I think it would be good to work out how to shift it into `elastic_responses` so anyone who's using this library directly can benefit. Plus it makes sense to keep all response parsing related stuff here.

With a bit of thought I think we can make it independent of `reqwest`/`hyper`. It really only needs to see a status code, which we can get as a `u16` and access to a byte buffer.

I think a trait might be a bit clunky because you the user probably can't implement it for `reqwest`s response type.

Any thoughts @stephanbuys?

**Comment by stephanbuys** [comment]
@KodrAus Agreed that this seems to be right at home with `elastic-responses`, a `trait` might be a cool idea, everything should work as long as it can be turned into a `serde_json::Value`, so a `ToSerdeJson` trait? (just riffing here on 2mins of thought), that could eliminate the need for reqwest, hyper, etc - something that I think is quite important as there will probably be some nice `async` clients coming out of the `tokio` project.

From your code it seems that you want to determine if it was a `get` or `query_dsl` response? My initial reaction was "how would you not know what kind of query you did?", can you elaborate a bit why you think this is necessary?

**Comment by stephanbuys** [comment]
I actually can see a nice `message passing`-like use-case for the idea above, where queries and responses are decoupled, this could be a great "enterprise/real-world" feature.

**Comment by KodrAus** [comment]
Ah the above code is more about trying to work out whether a response is a success type `T` or an error type `ApiError`. Unfortunately it's not enough to just check the HTTP status code in some cases, like trying to get a document for an index that doesn't exist.

That's a good point about message passing and async. If we break the steps that get you from a request to a response into logical chunks that work with messages that are `Send` then you could choose to run different parts in different ways. Like using `tokio` to manage io, then passing the raw response to some background workers to deserialise before returning the final result somewhere else.

Plus that would make the way these crates communicate more logical. I feel like it's a bit of a mishmash right now.

**Comment by stephanbuys** [comment]
Oh ok - if you have any examples you can point me to that would be awesome, I'd be happy to assist if I can.

As to the second part, I think that could be an incredibly powerful addition, submit a query, get handed a `Future` that will at some point resolve to a `Value`, we've often had to add another layer of to our client to manage queries/backoff/load-balancing, etc. This could be a great addition, speaking of which please see: https://github.com/elastic-rs/elastic/issues/165
